# Generated by Django 2.1.2 on 2020-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AlterField(
            model_name='branch',
            name='password',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
