# Generated by Django 2.1.2 on 2020-06-30 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0002_auto_20200629_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 18, 33, 7, 760982)),
        ),
    ]
