# Generated by Django 2.1.2 on 2020-06-30 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_account_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='visit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 23, 22, 59, 988413)),
        ),
        migrations.AlterUniqueTogether(
            name='cusemp',
            unique_together=set(),
        ),
    ]
